server:
  port: 9696


spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: 
    url: jdbc:h2:mem:test
    username: mohit
    
  mvc:
    view:
      prefix: /views/
      suffix: .jsp     

  app1 :
   messages :
        saveSuccess : Contact save Successfully
        saveFail : Constant Failed To Save
    